### ISSUE TITLE
Switch .Net Core to .Net Standard 2.0 or lower

### ISSUE THREAD

**Issue by 1dNDN** [SergeantSerk/MCQuery#2]
I think it's worth changing because .Net Standard 2.0 will greatly expand the list of supported platforms: https://docs.microsoft.com/en-us/dotnet/standard/net-standard
In addition, I think it is worth using the Net standard 2.0 version or even lower, because there is a large number of projects left on .Net Framework or on .Net Core 2.1, which cannot use older libraries .Net Standart 2.0.
An alternative solution is to build the library for several different platforms

**Comment by SergeantSerk** [comment]
This is a good suggestion, I did not think of this. It will expand usage across different .NET implementations and allows for older platforms to use this library.
